# Site settings
title: ALL Lego Robot Game
email: edward_prince@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  My IPP for the Lego Robot Project. Contains weekly updates of our progress with
  regards to our game. Powered by Jekyll and Github pages.
baseurl: "/lego/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  edprince

# Build settings
markdown: kramdown
